import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
// import "@radix-ui/themes/styles.css";
// import { Theme } from "@radix-ui/themes";
import "@mantine/core/styles.css";
import { MantineProvider, createTheme } from "@mantine/core";
import { ColorSchemeScript } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

const theme = createTheme({
	fontFamily: inter.style.fontFamily,
	primaryColor: 'violet'
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript />
			</head>
			{/* <body className={inter.className}> */}
			<body >
				<MantineProvider theme={theme}>
					<NavBar />
					<main className="p-5">{children}</main>
				</MantineProvider>
			</body>
		</html>
	);
}
